app: webhook
org: mkoskela
service: aws-node-typescript-sqs-standard

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - "dynamodb:PutItem"
            - "dynamodb:Get*"
            - "dynamodb:Scan*"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
          Resource:
            - Fn::GetAtt: [receiverQueue, Arn]
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-sender-${sls:stage}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-receiver-${sls:stage}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-getOrders-${sls:stage}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-ordersTable-${sls:stage}
  environment:
    DYNAMODB_ORDERS_TABLE: ${self:service}-ordersTable-${sls:stage}

functions:
  sender:
    handler: handler.sender
    events:
      - http:
          method: post
          path: sender

  receiver:
    handler: handler.receiver
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - receiverQueue
              - Arn

  getOrders:
    handler: getOrders.getOrders
    events:
      - httpApi:
          path: /getOrders
          method: get

resources:
  Resources:
    receiverQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: receiverQueue

    ordersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: sellerId
            AttributeType: S
          - AttributeName: orderId
            AttributeType: S
          - AttributeName: dateCreated
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: sellerId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: secondaryIndex
            KeySchema:
              - AttributeName: orderId
                KeyType: HASH
              - AttributeName: dateCreated
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
        TableName: ${self:service}-ordersTable-${sls:stage}
